/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summary */
        post: operations["summary_api_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checklists */
        get: operations["checklists_api_checklists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklists/{crime_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checklist */
        get: operations["checklist_api_checklists__crime_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_api_templates__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Support Questions */
        get: operations["support_questions_api_support_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Support Match
         * @description Match answers to support programs. A program matches when every declared
         *     criterion is satisfied; programs with no criteria always apply.
         */
        post: operations["support_match_api_support_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Centers */
        get: operations["centers_api_centers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback
         * @description Negative feedback becomes an eval candidate. Only the question text is
         *     kept — never the answer, and never anything the user typed about themselves
         *     beyond the question they chose to send.
         */
        post: operations["feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Client Error
         * @description Frontend crash reports (no user content). Grep logs for client_error to
         *     compute the crash-free session metric.
         */
        post: operations["client_error_api_client_error_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/procedure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Procedure */
        get: operations["procedure_api_procedure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deadlines */
        get: operations["deadlines_api_deadlines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Livez
         * @description Liveness: is the process running? (restart if this fails)
         */
        get: operations["livez_api_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: should this instance receive traffic? (data loaded, not draining)
         */
        get: operations["readyz_api_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CentersFile */
        CentersFile: {
            /** Note */
            note?: string | null;
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
            /** Verified On */
            verified_on: string;
            /** Hotlines */
            hotlines: components["schemas"]["Hotline"][];
            /** Regions */
            regions: components["schemas"]["RegionRow"][];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /**
             * Lang
             * @default ko
             * @enum {string}
             */
            lang: "ko" | "en";
            /**
             * Simple
             * @default false
             */
            simple: boolean;
        };
        /** Checklist */
        Checklist: {
            /** Label */
            label: string;
            /**
             * Urgent
             * @default []
             */
            urgent: components["schemas"]["ChecklistItem"][];
            /** Items */
            items: components["schemas"]["ChecklistItem"][];
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
        };
        /** ChecklistItem */
        ChecklistItem: {
            /** Item */
            item: string;
            /** Why */
            why?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** ClientError */
        ClientError: {
            /** Message */
            message: string;
            /** Stack */
            stack?: string | null;
            /** Url */
            url?: string | null;
        };
        /** DeadlineRule */
        DeadlineRule: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** From */
            from: string;
            /** Hours */
            hours?: number | null;
            /** Days */
            days?: number | null;
            /** Months */
            months?: number | null;
            /** Years */
            years?: number | null;
            /** Urgency */
            urgency: string;
            /** Desc */
            desc: string;
        };
        /** DeadlinesFile */
        DeadlinesFile: {
            /** Note */
            note?: string | null;
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
            /** Verified On */
            verified_on: string;
            /** Rules */
            rules: components["schemas"]["DeadlineRule"][];
        };
        /** EligibilityRequest */
        EligibilityRequest: {
            /** Answers */
            answers?: {
                [key: string]: unknown;
            };
        };
        /** Feedback */
        Feedback: {
            /** Helpful */
            helpful: boolean;
            /**
             * Question
             * @default
             */
            question: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hotline */
        Hotline: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Hours */
            hours: string;
            /** For */
            for: string;
        };
        /** ProcedureFile */
        ProcedureFile: {
            /** Note */
            note?: string | null;
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
            /** Verified On */
            verified_on: string;
            /** Stages */
            stages: components["schemas"]["Stage"][];
        };
        /** RegionRow */
        RegionRow: {
            /** Region */
            region: string;
            /** Klac */
            klac: string;
            /** Victim Center */
            victim_center: string;
            /** Sunflower */
            sunflower: string;
        };
        /** SourceLink */
        SourceLink: {
            /** Label */
            label: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** Stage */
        Stage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Desc */
            desc: string;
            /**
             * Rights
             * @default []
             */
            rights: string[];
            /**
             * Tips
             * @default
             */
            tips: string;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** SupportMatchResponse */
        SupportMatchResponse: {
            /** Matched */
            matched: components["schemas"]["SupportProgram"][];
            /** Others */
            others: components["schemas"]["SupportProgram"][];
            /** Notes */
            notes: string[];
            /** Disclaimer */
            disclaimer: string;
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
            /** Verified On */
            verified_on?: string | null;
        };
        /** SupportOption */
        SupportOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** SupportProgram */
        SupportProgram: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Who */
            who: string;
            /** What */
            what: string;
            /** How */
            how: string;
            /** Contact */
            contact: string;
            /** Sources */
            sources: components["schemas"]["SourceLink"][];
            /**
             * Match
             * @default {}
             */
            match: {
                [key: string]: string[];
            };
        };
        /** SupportQuestion */
        SupportQuestion: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Options */
            options: components["schemas"]["SupportOption"][];
        };
        /** SupportQuestionsResponse */
        SupportQuestionsResponse: {
            /** Note */
            note: string;
            /** Questions */
            questions: components["schemas"]["SupportQuestion"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-anthropic-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-anthropic-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checklists_api_checklists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    checklist_api_checklists__crime_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crime_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_api_templates__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    support_questions_api_support_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportQuestionsResponse"];
                };
            };
        };
    };
    support_match_api_support_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    centers_api_centers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CentersFile"];
                };
            };
        };
    };
    glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Feedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_error_api_client_error_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientError"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    procedure_api_procedure_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedureFile"];
                };
            };
        };
    };
    deadlines_api_deadlines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadlinesFile"];
                };
            };
        };
    };
    livez_api_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_api_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
